### ------------------------------------
GET http://localhost:3000

### ------------------------------------
GET http://localhost:3000/example
Content-Type: application/json

### ------------------------------------
GET http://localhost:3000/example/test
Content-Type: application/json

### ------------------------------------
POST  http://localhost:3000/example/score
Content-Type: application/json

{
  "User": "Example User",
  "highScore": 10
}

### ------------------------------------
POST  http://localhost:3000/auth
Content-Type: application/json

{
  "user": "ken",
  "password": "test123"
}

### ------------------------------------
POST  http://localhost:3000/logout
Content-Type: application/json

### ------------------------------------
POST http://localhost:3000/todos
Content-Type: application/json

[
  {
   "title": "Buy groceries",
   "isComplete": false
  }
]

### ------------------------------------
GET http://localhost:3000/todos
Content-Type: application/json

